<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto

namespace App\Grpc\Auth;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>auth.TokenRequest</code>
 */
class TokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     */
    protected $access_token = '';

    /**
     * Constructor.
     *
     * @param  array  $data  {
     *                       Optional. Data for populating the Message object.
     *
     * @type string $access_token
     *              }
     */
    public function __construct($data = null)
    {
        \App\Grpc\Auth\Metadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     *
     * @return string
     */
    public function getAccessToken()
    {
        return $this->access_token;
    }

    /**
     * Generated from protobuf field <code>string access_token = 1;</code>
     *
     * @return $this
     */
    public function setAccessToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->access_token = $var;

        return $this;
    }
}
